# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cellphone_number',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
