# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_cellphone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
